name: publish-linux-x64

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Publish
      run: |
        mkdir /tmp/publish
        dotnet publish server --self-contained true -p:PublishSingleFile=true --output /tmp/publish -p:PublishTrimmed=true -p:PublishReadyToRun=true
    
    - name: Upload manifest
      uses: actions/upload-artifact@v3
      with:
        name: server-executable-file
        path: |
          /tmp/publish/server
          /tmp/publish/appsettings.json
