name: publish

on: 
  workflow_dispatch:
    inputs:
      self-contained:
        required: true
        type: boolean
      publish-single-file:
        required: true
        type: boolean
      publish-ready-to-run:
        required: true
        type: boolean
    

jobs:
  publish:
    strategy:
        matrix:
          project: [ client, server ]
          platform: [ win-x64, win-x86, win-arm64, linux-x64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Publish
      run: |
        mkdir /tmp/publish
        dotnet publish ${{ matrix.project }}  --output /tmp/publish --runtime ${{ matrix.platform }} --self-contained ${{ format('{0}', inputs.self-contained) }} -p:PublishSingleFile=${{ format('{0}', inputs.publish-single-file) }} -p:PublishReadyToRun=${{ format('{0}', inputs.publish-ready-to-run) }}
        cd /tmp/publish
        zip -c -p ghg-online-${{ matrix.project }}-${{ matrix.platform }}.zip *
      
    - name: Upload manifest
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: /tmp/publish/ghg-online-${{ matrix.project }}-${{ matrix.platform }}.zip
